version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/photobook
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    depends_on:
      - db
      - backend

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/photobook
      - JWT_SECRET=your-jwt-secret
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=photobook
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: